language: java
jdk:
  - oraclejdk7
branches:
  only:
  - master
before_install:
  - "export TERM=dumb"
install: ./gradlew clean resolveAllDependencies assemble
script: ./gradlew test
    && ./gradlew cucumber
    && ./gradlew uploadSnapshots
env:
  global:
    - secure: "UMajdsEYj4wB7zs06WsZxxtsN6n14iVRgKwtIjUzWBcNOWKfUXQV7o5eHqoBpTRSEBiLbA9MOi7yAQDIZalH9vJI6z0Aqyvp+EQyytNTAS8RMfMp8G7iEhf26bYjSZaW0VgTDsYgMciTIdPlZ5oyjBoKpd6Iqo9HwPmZxtBQWvE="
    - secure: "MZH6u8Q83/D/HPYaDMs6bpMJfmAHhGlS5yYGwUL4JZ64AsrkhtV19unXKs0Wp7+BuVjHMPEhqdWEEV9i7a/KrIqKwMQUJ8+JyAFzwdOCbCE+39FiKW7clQQ1pRj4dXLNrGAV3UalDCxU5KtCXfg/co6MPG3b3jBUYILvQ9ccQeY="


