language: java
jdk:
  - oraclejdk7
branches:
  only:
  - master
before_install:
  - "export TERM=dumb"
install: ./gradlew clean assemble
script: ./gradlew test
    && ./gradlew cucumber
    && ./gradlew -i uploadSnapshots --stacktrace
env:
  global:
    - secure: "CeOHuydi4kWGV1i/EAxDdaUiKLMsIcUGJ8hR8mCaX9Y1uC+nLgSKF5q5sMCRaOEnJZ1v4KiuEpk6ZXPYW4xWFHKPwpk9pNQJIDUBFGU1wnjcs/ULCYGR7iuufNcp7bw5lI0Zy6f5Dl1op1/oC+kVozztPBYD3nWI7jwiBV8Ydgs="
    - secure: "Qeaj/lDE9+BL51ql5ZLtSIj8acM/VPQuF7g+PgPbuMVE0B5J/62Xw4zjPm+6UJ8r3RoUtQkUnuh2ESCwpvMhDXE7ULeYpMIhKHTC2wDTjdQwBckUzVvStHXQxDjkYsFET4jxTagb79DdkpKRD5qjDdAOQTEyOEkdl6opjlQZOpE="


